# Generated by Django 5.0.1 on 2024-02-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.TextField(max_length=255),
        ),
    ]
