# Generated by Django 5.0.1 on 2024-02-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('city', models.TextField()),
                ('country', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
